[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/.well-known/farcaster.json"
  status = 200
  headers = { Content-Type = "application/json" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
